version: '3'

services:
  poll:
    build: ./poll
    ports:
      - 5000:80
    networks:
      - poll-tier
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    links:
      - redis
      - db

  redis:
    image: redis:buster
    expose:
      - 6379
    ports:
      - 6379:6379
    networks:
      - poll-tier
      - back-tier
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

  worker:
      build: ./worker/
      networks:
        - back-tier
      deploy:
        restart_policy:
          condition: on-failure
          max_attempts: 3

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      PGDATA: db-data:/var/lib/postgresql/data
    networks:
      - result-tier
      - back-tier
    volumes:
      - db-data:/var/lib/postgresql/data
      - "./schema.sql:/docker-entrypoint-initdb.d/init.sql"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

  result:
      build: ./result/
      ports:
        - 5001:80
      networks:
        - result-tier
      deploy:
        restart_policy:
          condition: on-failure
          max_attempts: 3

volumes:
  db-data:

networks:
  poll-tier:
  result-tier:
  back-tier: