version: '3'

services:
  poll:
    build: ./poll
    ports:
      - 5000:80
    networks:
      - poll-tier
    depends_on:
      - redis
    restart: always
    links:
      - redis
      - db
  redis:
    image: redis:buster
    expose:
      - 6379
    ports:
      - 6379:6379
    networks:
      - poll-tier
      - back-tier
    restart: always

  worker:
      build: ./worker/
      networks:
        - back-tier
      restart: always

  db:
    image: postgres
    restart: always
    networks:
      - result-tier
      - back-tier
    volumes:
      - db-data:/var/lib/postgresql/data
      - "./schema.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=password"

  result:
      build: ./result/
      ports:
        - 5001:80
      networks:
        - result-tier
      restart: always
volumes:
  db-data:

networks:
  poll-tier:
  result-tier:
  back-tier: